server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/identity_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  signerKey: "KOX/fR5t6kwik5fNnaoNCEe9tJFxcIqAHxUP82D1Pzy/YflIqgBnN26FkUd9kbPz"
  valid-duration: 3600
  refreshable-duration: 36000

app:
  services:
    profile: http://localhost:8081/profile